### ISSUE TITLE
Evaluate exercice code

### ISSUE THREAD

**Issue by thomasdenecker** [IFB-ElixirFr/Wasm4Learn#30]
# Code location

https://github.com/IFB-ElixirFr/Wasm4Learn/blob/f87f121f52a3adf7a036f2e0c33a8909a81f21e7/pages/language/%5Blang%5D/%5B...slug%5D.vue#L329C5-L342C1

# Mission

Do only for R

**Comment by imanemessak** [comment]
fixed here #32
